[package]
name = "http_request_waki"
version = "0.1.0"
edition = "2021"

[dependencies]
waki = { version = "0.5.0", features = ["json", "multipart"] }
serde = { version = "1.0.202", features = ["derive"] }
anyhow = "1"

[profile.release]
opt-level = "s"
debug = false
strip = true
lto = true
