[package]
name = "http_request"
version = "0.1.0"
edition = "2021"

[dependencies]


[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true
